name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Lint
      run: |
        php --version
        find . -name "*.php" -print0 | xargs -0 -n1 php -l
